# Generated by Django 5.2.1 on 2025-05-16 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadBox',
            fields=[
                ('idDisponibilidadBox', models.BigAutoField(primary_key=True, serialize=False)),
                ('disponibilidad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Disponibilidad Box',
                'verbose_name_plural': 'Disponibilidades Box',
                'db_table': 'DisponibilidadBox',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idEspecialidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreEspecialidad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'Especialidad',
            },
        ),
        migrations.CreateModel(
            name='EstadoConsulta',
            fields=[
                ('idEstadoConsulta', models.BigAutoField(primary_key=True, serialize=False)),
                ('estadoConsulta', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado Consulta',
                'verbose_name_plural': 'Estados Consulta',
                'db_table': 'EstadoConsulta',
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('idJornada', models.BigAutoField(primary_key=True, serialize=False)),
                ('jornadaInicio', models.TimeField()),
                ('jornadaFin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'db_table': 'Jornada',
            },
        ),
        migrations.CreateModel(
            name='TipoBox',
            fields=[
                ('idTipoBox', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipoBox', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo Box',
                'verbose_name_plural': 'Tipos Box',
                'db_table': 'TipoBox',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('idBox', models.BigAutoField(primary_key=True, serialize=False)),
                ('numeroBox', models.IntegerField()),
                ('disponibilidadBox', models.ForeignKey(db_column='idDisponibilidadBox', on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='boxes.disponibilidadbox')),
                ('tipoBox', models.ForeignKey(db_column='idTipoBox', on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='boxes.tipobox')),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxes',
                'db_table': 'Box',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idMedico', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(max_length=200)),
                ('especialidad', models.ForeignKey(db_column='idEspecialidad', on_delete=django.db.models.deletion.PROTECT, related_name='medicos', to='boxes.especialidad')),
                ('jornada', models.ForeignKey(db_column='idJornada', on_delete=django.db.models.deletion.PROTECT, related_name='medicos', to='boxes.jornada')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'db_table': 'Medico',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idConsulta', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechaHoraInicio', models.DateTimeField()),
                ('fechaHoraFin', models.DateTimeField()),
                ('box', models.ForeignKey(db_column='idBox', on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='boxes.box')),
                ('estadoConsulta', models.ForeignKey(db_column='idEstadoConsulta', on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='boxes.estadoconsulta')),
                ('medico', models.ForeignKey(db_column='idMedico', on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='boxes.medico')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'Consulta',
            },
        ),
    ]
