# Generated by Django 5.2.1 on 2025-05-17 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadBox',
            fields=[
                ('idDisponibilidadBox', models.AutoField(db_column='idDisponibilidadBox', primary_key=True, serialize=False)),
                ('disponibilidad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'DisponibilidadBox',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idEspecialidad', models.AutoField(db_column='idEspecialidad', primary_key=True, serialize=False)),
                ('nombreEspecialidad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Especialidad',
            },
        ),
        migrations.CreateModel(
            name='EstadoConsulta',
            fields=[
                ('idEstadoConsulta', models.AutoField(db_column='idEstadoConsulta', primary_key=True, serialize=False)),
                ('estadoConsulta', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'EstadoConsulta',
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('idJornada', models.AutoField(db_column='idJornada', primary_key=True, serialize=False)),
                ('jornadaInicio', models.TimeField()),
                ('jornadaFin', models.TimeField()),
            ],
            options={
                'db_table': 'Jornada',
            },
        ),
        migrations.CreateModel(
            name='Pasillo',
            fields=[
                ('idPasillo', models.AutoField(db_column='idPasillo', primary_key=True, serialize=False)),
                ('nombrePasillo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Pasillo',
            },
        ),
        migrations.CreateModel(
            name='TipoBox',
            fields=[
                ('idTipoBox', models.AutoField(db_column='idTipoBox', primary_key=True, serialize=False)),
                ('tipoBox', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TipoBox',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('idBox', models.AutoField(db_column='idBox', primary_key=True, serialize=False)),
                ('disponibilidadBox', models.ForeignKey(db_column='idDisponibilidadBox', on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='boxes.disponibilidadbox')),
            ],
            options={
                'db_table': 'Box',
            },
        ),
        migrations.CreateModel(
            name='BoxEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.ForeignKey(db_column='idBox', on_delete=django.db.models.deletion.CASCADE, to='boxes.box')),
                ('especialidad', models.ForeignKey(db_column='idEspecialidad', on_delete=django.db.models.deletion.CASCADE, to='boxes.especialidad')),
            ],
            options={
                'db_table': 'BoxEspecialidad',
                'unique_together': {('box', 'especialidad')},
            },
        ),
        migrations.AddField(
            model_name='box',
            name='especialidades',
            field=models.ManyToManyField(related_name='boxes', through='boxes.BoxEspecialidad', to='boxes.especialidad'),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idMedico', models.AutoField(db_column='idMedico', primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(max_length=200)),
                ('especialidad', models.ForeignKey(db_column='idEspecialidad', on_delete=django.db.models.deletion.PROTECT, related_name='medicos', to='boxes.especialidad')),
                ('jornada', models.ForeignKey(db_column='idJornada', on_delete=django.db.models.deletion.PROTECT, related_name='medicos', to='boxes.jornada')),
            ],
            options={
                'db_table': 'Medico',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idConsulta', models.AutoField(db_column='idConsulta', primary_key=True, serialize=False)),
                ('fechaHoraInicio', models.DateTimeField()),
                ('fechaHoraFin', models.DateTimeField()),
                ('box', models.ForeignKey(db_column='idBox', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='boxes.box')),
                ('estadoConsulta', models.ForeignKey(db_column='idEstadoConsulta', on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='boxes.estadoconsulta')),
                ('medico', models.ForeignKey(db_column='idMedico', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='boxes.medico')),
            ],
            options={
                'db_table': 'Consulta',
            },
        ),
        migrations.AddField(
            model_name='box',
            name='medico',
            field=models.ForeignKey(blank=True, db_column='idMedico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='boxes.medico'),
        ),
        migrations.AddField(
            model_name='box',
            name='pasillo',
            field=models.ForeignKey(db_column='idPasillo', on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='boxes.pasillo'),
        ),
        migrations.AddField(
            model_name='box',
            name='tipoBox',
            field=models.ForeignKey(db_column='idTipoBox', on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='boxes.tipobox'),
        ),
    ]
