# Generated by Django 5.2.1 on 2025-05-23 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadBox',
            fields=[
                ('id', models.AutoField(db_column='idDisponibilidadBox', primary_key=True, serialize=False)),
                ('disponibilidad', models.CharField(choices=[('Habilitado', 'Habilitado'), ('Inhabilitado', 'Inhabilitado')], db_column='disponibilidad', max_length=15, unique=True)),
            ],
            options={
                'db_table': 'DisponibilidadBox',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(db_column='idEspecialidad', primary_key=True, serialize=False)),
                ('nombreEspecialidad', models.CharField(db_column='nombreEspecialidad', max_length=100)),
            ],
            options={
                'db_table': 'Especialidad',
            },
        ),
        migrations.CreateModel(
            name='EstadoConsulta',
            fields=[
                ('id', models.AutoField(db_column='idEstadoConsulta', primary_key=True, serialize=False)),
                ('estadoConsulta', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada'), ('Confirmada', 'Confirmada')], db_column='estadoConsulta', max_length=15, unique=True)),
            ],
            options={
                'db_table': 'EstadoConsulta',
            },
        ),
        migrations.CreateModel(
            name='Pasillo',
            fields=[
                ('id', models.AutoField(db_column='idPasillo', primary_key=True, serialize=False)),
                ('nombrePasillo', models.CharField(db_column='nombrePasillo', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Pasillo',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(db_column='idBox', primary_key=True, serialize=False)),
                ('disponibilidadBox', models.ForeignKey(db_column='idDisponibilidadBox', on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='boxes.disponibilidadbox')),
            ],
            options={
                'db_table': 'Box',
            },
        ),
        migrations.CreateModel(
            name='BoxEspecialidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('box', models.ForeignKey(db_column='idBox', on_delete=django.db.models.deletion.CASCADE, to='boxes.box')),
                ('especialidad', models.ForeignKey(db_column='idEspecialidad', on_delete=django.db.models.deletion.CASCADE, to='boxes.especialidad')),
            ],
            options={
                'db_table': 'BoxEspecialidad',
            },
        ),
        migrations.AddField(
            model_name='box',
            name='especialidades',
            field=models.ManyToManyField(related_name='boxes', through='boxes.BoxEspecialidad', to='boxes.especialidad'),
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(db_column='idJornada', primary_key=True, serialize=False)),
                ('jornadaInicio', models.TimeField()),
                ('jornadaFin', models.TimeField()),
            ],
            options={
                'db_table': 'Jornada',
                'indexes': [models.Index(fields=['jornadaInicio', 'jornadaFin'], name='Jornada_jornada_0d9cbb_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('jornadaFin__gt', models.F('jornadaInicio'))), name='jornada_fin_gt_inicio')],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(db_column='idMedico', primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(db_column='nombreCompleto', db_index=True, max_length=120)),
                ('especialidad', models.ForeignKey(db_column='idEspecialidad', on_delete=django.db.models.deletion.PROTECT, related_name='medicos', to='boxes.especialidad')),
                ('jornada', models.ForeignKey(db_column='idJornada', on_delete=django.db.models.deletion.PROTECT, related_name='medicos', to='boxes.jornada')),
            ],
            options={
                'db_table': 'Medico',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(db_column='idConsulta', primary_key=True, serialize=False)),
                ('fechaHoraInicio', models.DateTimeField()),
                ('fechaHoraFin', models.DateTimeField()),
                ('box', models.ForeignKey(db_column='idBox', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='boxes.box')),
                ('estadoConsulta', models.ForeignKey(db_column='idEstadoConsulta', on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='boxes.estadoconsulta')),
                ('medico', models.ForeignKey(db_column='idMedico', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='boxes.medico')),
            ],
            options={
                'db_table': 'Consulta',
            },
        ),
        migrations.AddField(
            model_name='box',
            name='pasillo',
            field=models.ForeignKey(db_column='idPasillo', on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='boxes.pasillo'),
        ),
        migrations.AddIndex(
            model_name='boxespecialidad',
            index=models.Index(fields=['especialidad'], name='BoxEspecial_idEspec_e7f491_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boxespecialidad',
            unique_together={('box', 'especialidad')},
        ),
        migrations.AddIndex(
            model_name='medico',
            index=models.Index(fields=['especialidad'], name='Medico_idEspec_81fe51_idx'),
        ),
        migrations.AddIndex(
            model_name='medico',
            index=models.Index(fields=['jornada'], name='Medico_idJorna_a33f62_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['fechaHoraInicio', 'box'], name='Consulta_fechaHo_47da1f_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['fechaHoraInicio', 'estadoConsulta'], name='Consulta_fechaHo_28327f_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['medico'], name='Consulta_idMedic_3cd872_idx'),
        ),
        migrations.AddConstraint(
            model_name='consulta',
            constraint=models.CheckConstraint(condition=models.Q(('fechaHoraFin__gt', models.F('fechaHoraInicio'))), name='consulta_fin_gt_inicio'),
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['pasillo'], name='Box_idPasil_32928d_idx'),
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['disponibilidadBox'], name='Box_idDispo_6b0b98_idx'),
        ),
    ]
