# Generated by Django 5.2.1 on 2025-05-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={},
        ),
        migrations.AlterModelOptions(
            name='disponibilidadbox',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipobox',
            options={},
        ),
    ]
