# Generated by Django 5.2.1 on 2025-05-17 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(blank=True, db_column='idMedico', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='boxes.medico'),
        ),
    ]
