# Generated by Django 5.2.1 on 2025-05-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.AutoField(db_column='idAsignacionTurno', primary_key=True, serialize=False)),
                ('fechaHoraInicio', models.DateTimeField()),
                ('fechaHoraFin', models.DateTimeField()),
                ('box', models.ForeignKey(db_column='idBox', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_turno', to='boxes.box')),
                ('medico', models.ForeignKey(db_column='idMedico', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_turno', to='boxes.medico')),
            ],
            options={
                'db_table': 'AsignacionTurno',
                'indexes': [models.Index(fields=['fechaHoraInicio', 'box'], name='AsignacionT_fechaHo_847e55_idx'), models.Index(fields=['medico'], name='AsignacionT_idMedic_033a58_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fechaHoraFin__gt', models.F('fechaHoraInicio'))), name='asignacion_turno_fin_gt_inicio')],
            },
        ),
    ]
