# Generated by Django 5.2.1 on 2025-05-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_alter_box_options_alter_disponibilidadbox_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name': 'Box', 'verbose_name_plural': 'Boxes'},
        ),
        migrations.AlterModelOptions(
            name='disponibilidadbox',
            options={'verbose_name': 'Disponibilidad Box', 'verbose_name_plural': 'Disponibilidades Box'},
        ),
        migrations.AlterModelOptions(
            name='tipobox',
            options={'verbose_name': 'Tipo Box', 'verbose_name_plural': 'Tipos Box'},
        ),
    ]
